
import type { User, Item, Category, Conversation, ChatMessage, ExchangeRequest, Notification, AppCategory, Location, RepairShop } from './types';
import { Smartphone, Laptop, Keyboard, Monitor, Cable, Headphones, MemoryStick, SquarePlus, Gamepad2, ToyBrick } from 'lucide-react';

export const users: User[] = [
  {
    id: "user_01",
    userId: "user_01",
    displayName: "Rohan Kumar",
    email: "rohan.k@example.com",
    photoURL: "https://i.pravatar.cc/150?u=rohan",
    createdAt: new Date("2025-10-04T13:10:00"),
    lastKnownLocality: "kothrud",
    averageRating: 4.8,
    ratingsCount: 12,
    isTrusted: true,
    wishlist: ['item-3']
  },
  {
    id: "user_02",
    userId: "user_02",
    displayName: "Anjali Sharma",
    email: "anjali.s@example.com",
    photoURL: "https://i.pravatar.cc/150?u=anjali",
    createdAt: new Date("2025-10-03T09:30:00"),
    lastKnownLocality: "viman-nagar",
    averageRating: 4.9,
    ratingsCount: 8,
    isTrusted: true,
    wishlist: []
  },
  {
    id: "user_03",
    userId: "user_03",
    displayName: "Vikram Singh",
    email: "vikram.s@example.com",
    photoURL: null,
    createdAt: new Date("2025-10-01T17:00:00"),
    lastKnownLocality: "hadapsar",
    averageRating: 4.5,
    ratingsCount: 4,
    isTrusted: false,
    wishlist: []
  },
  {
    id: "user_04",
    userId: "user_04",
    displayName: "Priya Deshmukh",
    email: "priya.d@example.com",
    photoURL: "https://i.pravatar.cc/150?u=priya",
    createdAt: new Date("2025-09-28T11:00:00"),
    lastKnownLocality: "deccan-gymkhana",
    averageRating: 4.7,
    ratingsCount: 15,
    isTrusted: true,
    wishlist: []
  },
  {
    id: "user_05",
    userId: "user_05",
    displayName: "Rahul Khanna",
    email: "rahul.k@example.com",
    photoURL: 'https://i.pravatar.cc/150?u=rahul',
    createdAt: new Date("2025-09-25T18:20:00"),
    lastKnownLocality: "koregaon-park",
    averageRating: 4.6,
    ratingsCount: 5,
    isTrusted: false,
    wishlist: []
  },
  {
    id: "user_06",
    userId: "user_06",
    displayName: "Deepak Patil",
    email: "deepak.p@example.com",
    photoURL: "https://i.pravatar.cc/150?u=deepak",
    createdAt: new Date("2025-09-22T12:00:00"),
    lastKnownLocality: "wakad",
    averageRating: 4.6,
    ratingsCount: 9,
    isTrusted: false,
    wishlist: []
  }
];

export const items: Item[] = [
  {
    id: 'item-1',
    title: "Dell XPS 13 Laptop (2020 Model)",
    description: "Good condition, works perfectly for coding and daily use. Has a few minor scratches on the lid. Comes with original charger.",
    category: "laptops",
    brand: "Dell",
    condition: "Working",
    listingType: "Sell",
    price: 35000,
    imageUrls: ["https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc4/Dell-XPS-13-9340-laptop.JPG"],
    locality: "kothrud",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date("2025-10-04T13:15:00")
  },
  {
    id: 'item-2',
    title: "Apple iPhone X - For Donation",
    description: "Apple iPhone X, needs minor repair (e.g., screen crack, battery replacement). Donating for someone to fix or use for parts. Device is unlocked.",
    category: "mobiles",
    brand: "Apple",
    condition: "Needs Minor Repair",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://d57avc95tvxyg.cloudfront.net/images/detailed/2449/full_body_housing_for_apple_iphone_x_256gb_gold_maxbhi_com_52886.jpg?t=1540011330"],
    locality: "viman-nagar",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: true,
    createdAt: new Date("2025-10-04T10:00:00")
  },
  {
    id: 'item-3',
    title: "Logitech Mechanical Gaming Keyboard",
    description: "Logitech G815 Low Profile Mechanical Gaming Keyboard. Tactile switches. Fully functional, RGB lighting works perfectly. Selling as I'm switching to a smaller keyboard.",
    category: "keyboards",
    brand: "Logitech",
    condition: "Working",
    listingType: "Sell",
    price: 2500,
    imageUrls: ["https://i.redd.it/xd1j3t6tqnj31.jpg"],
    locality: "hadapsar",
    ownerId: "user_03",
    ownerName: "Vikram Singh",
    ownerAvatarUrl: null,
    ownerRating: 4.5,
    status: "Available",
    isFeatured: false,
    createdAt: new Date("2025-10-03T20:00:00")
  },
  {
    id: 'item-4',
    title: "Samsung 24-inch Monitor (for parts)",
    description: "Samsung 24-inch monitor. The display panel is faulty and does not turn on. Good for someone who can repair it or use the stand, casing, or internal components for spare parts.",
    category: "monitors",
    brand: "Samsung",
    condition: "For Spare Parts Only",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://images.offerup.com/iWYFo-lWu_fk865kEqJyWT6GON8=/1000x563/edc0/edc0e6a2e25b4a9298f99c91fad23433.jpg"],
    locality: "viman-nagar",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: false,
    createdAt: new Date("2025-10-02T11:00:00")
  },
  {
    id: 'item-5',
    title: "Box of Assorted Cables and Chargers",
    description: "A box full of various cables (USB, HDMI, audio) and chargers (phone, laptop - older models). Donating to help declutter and for someone who might need specific connectors.",
    category: "cables",
    brand: "Assorted",
    condition: "Working",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://www.shutterstock.com/image-photo/organized-box-containing-assorted-cables-260nw-2485719485.jpg"],
    locality: "kothrud",
    ownerId: "user_03",
    ownerName: "Vikram Singh",
    ownerAvatarUrl: null,
    ownerRating: 4.5,
    status: "Available",
    isFeatured: false,
    createdAt: new Date("2025-10-01T14:00:00")
  },
   {
    id: 'item-6',
    title: "Sony Noise-Cancelling Headphones",
    description: "Sony WH-1000XM4 Wireless Noise-Cancelling Headphones. Excellent sound quality and industry-leading noise cancellation. Perfect for travel or focused work. Comes with original case and cables.",
    category: "audio",
    brand: "Sony",
    condition: "Working",
    listingType: "Sell",
    price: 8000,
    imageUrls: ["https://static.digit.in/default/58b4111872ade143c01855ed50fced057bed51af.jpeg"],
    locality: "baner",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: true,
    createdAt: new Date("2025-10-04T14:00:00")
  },
  {
    id: "item-7",
    title: "RAM 8GB DDR4 Laptop",
    description: "Single 8GB stick of DDR4 RAM for laptops. Pulled from a working HP Pavilion. Speed is 2400MHz. Perfect for an upgrade.",
    category: "components",
    brand: "Crucial",
    condition: "Working",
    listingType: "Sell",
    price: 1500,
    imageUrls: ["https://rukminim2.flixcart.com/image/480/640/xif0q/ram/r/4/z/8gb-ddr4-2666-sodimm-1-2v-cl19-crucial-original-imahap4fwtqgmzph.jpeg?q=90"],
    locality: "kothrud",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-8",
    title: "Fujifilm X-T4 Mirrorless Camera",
    description: "Excellent condition, barely used. Comes with the original box, battery, and charger. No lens included. Shutter count is below 5000.",
    category: "other",
    brand: "Fujifilm",
    condition: "Working",
    listingType: "Sell",
    price: 85000,
    imageUrls: ["https://picsum.photos/seed/item8/600/400"],
    locality: "viman-nagar",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: true,
    createdAt: new Date()
  },
  {
    id: "item-9",
    title: "Redmi Note 9 Pro",
    description: "Redmi Note 9 Pro in good condition, needs minor repair like a battery replacement or minor screen buff. Fully functional otherwise. Great value phone.",
    category: "mobiles",
    brand: "Xiaomi",
    condition: "Needs Minor Repair",
    listingType: "Sell",
    price: 7000,
    imageUrls: ["https://sm.mashable.com/t/mashable_in/photo/default/redmi-phone02_rnuy.1248.jpg"],
    locality: "hadapsar",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-10",
    title: "Mi TV One (43 inch)",
    description: "4K Smart TV. The display panel is broken and shows vertical lines. The sound and smart features work fine. Good for someone who can repair the screen or use the internal parts.",
    category: "monitors",
    brand: "Xiaomi",
    condition: "For Spare Parts Only",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://picsum.photos/seed/item10/600/400"],
    locality: "baner",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-11",
    title: "iPhone 12 Pro Max, GOLDEN edition",
    description: "iPhone 12 Pro Max in a stunning GOLDEN edition. Fully functional, excellent condition. Selling due to upgrade. Includes original box and charging cable.",
    category: "mobiles",
    brand: "Apple",
    condition: "Working",
    listingType: "Sell",
    price: 42000,
    imageUrls: [
      "https://i.insider.com/5fad82d9343ad40018a93811?width=800&format=jpeg&auto=webp"
    ],
    locality: "koregaon-park",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: true,
    createdAt: new Date()
  },
  {
    id: "item-12",
    title: "Sony PlayStation 5 (PS5) Disc Edition",
    description: "Almost new PS5 Disc Edition. Used only a handful of times. Comes with one controller and all original cables.",
    category: "gaming",
    brand: "Sony",
    condition: "Working",
    listingType: "Sell",
    price: 45000,
    imageUrls: ["https://picsum.photos/seed/item12/600/400"],
    locality: "hinjawadi",
    ownerId: "user_03",
    ownerName: "Vikram Singh",
    ownerAvatarUrl: null,
    ownerRating: 4.5,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-13",
    title: "Power Supply Unit (PSU) for Desktop",
    description: "Corsair CV650, 650 Watt 80+ Bronze Certified Power Supply. Fully functional, pulled from an old gaming PC build.",
    category: "components",
    brand: "Corsair",
    condition: "Working",
    listingType: "Sell",
    price: 3000,
    imageUrls: ["https://3dwombat.com/cblog/wp-content/uploads/2017/11/OCZ_600W_power_supply_unit_resize2.jpg"],
    locality: "pimpri-chinchwad",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-14",
    title: "Nikon D5600 DSLR Camera",
    description: "Great for beginners. In good working order. Selling the body only, no lens or memory card included.",
    category: "other",
    brand: "Nikon",
    condition: "Working",
    listingType: "Sell",
    price: 28000,
    imageUrls: ["https://picsum.photos/seed/item14/600/400"],
    locality: "deccan-gymkhana",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-15",
    title: "OnePlus 8 Pro",
    description: "OnePlus 8 Pro in excellent condition. High-refresh-rate display and powerful performance. Selling due to an upgrade. Includes original box and charger.",
    category: "mobiles",
    brand: "OnePlus",
    condition: "Working",
    listingType: "Sell",
    price: 25000,
    imageUrls: ["https://telecomtalk.info/wp-content/uploads/2020/06/oneplus-8-pro-review-2-900x900.jpg"],
    locality: "kothrud",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-16",
    title: "SSD 256GB SATA",
    description: "Basic 256GB SATA SSD. Good for a boot drive or to speed up an old laptop. Health is good, checked with CrystalDiskInfo.",
    category: "components",
    brand: "Crucial",
    condition: "Working",
    listingType: "Sell",
    price: 1200,
    imageUrls: ["https://m.media-amazon.com/images/I/81oM9+mefcL.jpg"],
    locality: "viman-nagar",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-17",
    title: "GPU GTX 1050 Ti 4GB",
    description: "NVIDIA GeForce GTX 1050 Ti with 4GB GDDR5 VRAM. Excellent condition, great for casual gaming or as a display output. Cleaned and tested.",
    category: "components",
    brand: "NVIDIA",
    condition: "Working",
    listingType: "Sell",
    price: 6000,
    imageUrls: ["https://www.bhphotovideo.com/images/fb/msi_gtx_1050_ti_gaming_x_4g_geforce_gtx_1050_ti_1292076.jpg"],
    locality: "deccan-gymkhana",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-18",
    title: "Sony Alpha a6000 Mirrorless Camera",
    description: "Compact and powerful. Great for photography enthusiasts. Comes with a standard 16-50mm kit lens. Minor cosmetic wear.",
    category: "other",
    brand: "Sony",
    condition: "Working",
    listingType: "Sell",
    price: 30000,
    imageUrls: ["https://picsum.photos/seed/item18/600/400"],
    locality: "koregaon-park",
    ownerId: "user_05",
    ownerName: "Rahul Khanna",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rahul",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: true,
    createdAt: new Date()
  },
  {
    id: "item-19",
    title: "LG Smart TV (55 inch) - Faulty Panel",
    description: "55-inch LG Smart TV. Works, but has a large black patch on the left side of the screen. Good for parts or if you can replace the panel.",
    category: "monitors",
    brand: "LG",
    condition: "For Spare Parts Only",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://picsum.photos/seed/item19/600/400"],
    locality: "deccan-gymkhana",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-20",
    title: "Motherboard (ASUS B450)",
    description: "ASUS B450 motherboard, compatible with AMD Ryzen processors. Good condition, ideal for a budget or mid-range build. Comes with I/O shield.",
    category: "components",
    brand: "ASUS",
    condition: "Working",
    listingType: "Sell",
    price: 4500,
    imageUrls: [
      "https://dlcdnwebimgs.asus.com/files/media/53D30A49-0B79-48F2-AD43-DEB7F954AE2B/v1/img/kv/ROG-Strix-B760-F-Gaming.png"
    ],
    locality: "wakad",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-21",
    title: "Nintendo Switch Lite (Blue)",
    description: "Lightly used Nintendo Switch Lite in the blue/turquoise color. Perfect for handheld gaming. Comes with the original charger and a protective case. No games included.",
    category: "gaming",
    brand: "Nintendo",
    condition: "Working",
    listingType: "Sell",
    price: 14000,
    imageUrls: ["https://i.ebayimg.com/images/g/fs8AAOSwy29hh3L-/s-l1200.jpg"],
    locality: "hinjawadi",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-22",
    title: "Mi LED Smart Bulb (Color)",
    description: "Wi-Fi enabled smart bulb. Works with Google Assistant/Alexa. Used for a few months, selling as I switched to a different system.",
    category: "other",
    brand: "Xiaomi",
    condition: "Working",
    listingType: "Sell",
    price: 700,
    imageUrls: ["https://picsum.photos/seed/item22/600/400"],
    locality: "kothrud",
    ownerId: "user_03",
    ownerName: "Vikram Singh",
    ownerAvatarUrl: null,
    ownerRating: 4.5,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-23",
    title: "Xbox Series S Console",
    description: "Xbox Series S in excellent, like-new condition. Perfect for digital gaming with Game Pass. Comes with one white controller and all original cables (HDMI and power).",
    category: "gaming",
    brand: "Microsoft",
    condition: "Working",
    listingType: "Sell",
    price: 22000,
    imageUrls: ["https://cdn.stamped.io/uploads/photos/79323_6785_c900cbda_7a2e_49cb_93b4_e8bc526a7dc2.jpg?v="],
    locality: "viman-nagar",
    ownerId: "user_04",
    ownerName: "Priya Deshmukh",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=priya",
    ownerRating: 4.7,
    status: "Available",
    isFeatured: true,
    createdAt: new Date()
  },
  {
    id: "item-24",
    title: "Logitech C920 Webcam",
    description: "Full HD 1080p webcam. Great for online meetings or streaming. Works perfectly, comes with original box.",
    category: "other",
    brand: "Logitech",
    condition: "Working",
    listingType: "Sell",
    price: 2500,
    imageUrls: ["https://picsum.photos/seed/item24/600/400"],
    locality: "baner",
    ownerId: "user_05",
    ownerName: "Rahul Khanna",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rahul",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-25",
    title: "CPU Intel Core i5-9400F",
    description: "Intel Core i5-9400F 6-core processor. Excellent performance for gaming and everyday tasks. Requires a dedicated graphics card (no integrated graphics).",
    category: "components",
    brand: "Intel",
    condition: "Working",
    listingType: "Sell",
    price: 9000,
    imageUrls: ["https://cdn.mos.cms.futurecdn.net/SoVmUbfbrWzFsuHX4BBBab.jpg"],
    locality: "hadapsar",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-26",
    title: "MacBook Air M1 (2020) - Silver",
    description: "Excellent condition MacBook Air M1, 2020 model in Silver. Works flawlessly for creative tasks and daily use. Selling due to upgrade. Comes with original charger and box.",
    category: "laptops",
    brand: "Apple",
    condition: "Working",
    listingType: "Sell",
    price: 65000,
    imageUrls: ["https://www.cnet.com/a/img/resize/d93ef048db2ddb3e1a0fe8ee3f0c90f70a3c4150/hub/2020/11/16/a8e0e691-035a-4298-8366-f3b74e1f3792/img-1759.jpg?auto=webp&fit=crop&height=1200&width=1200"],
    locality: "kothrud",
    ownerId: "user_02",
    ownerName: "Priya Sharma",
    ownerAvatarUrl: null,
    ownerRating: 4.9,
    status: "Available",
    isFeatured: true,
    createdAt: new Date()
  },
  {
    id: "item-27",
    title: "Samsung Galaxy Tab A8",
    description: "Entry-level tablet for casual use. Wi-Fi model, 4GB RAM, 64GB storage. Perfect for kids or media consumption. No charger.",
    category: "other",
    brand: "Samsung",
    condition: "Working",
    listingType: "Sell",
    price: 10000,
    imageUrls: ["https://picsum.photos/seed/item27/600/400"],
    locality: "viman-nagar",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-28",
    title: "Google Pixel Buds A-Series",
    description: "Google Pixel Buds A-Series in-ear headphones. Great sound quality and comfortable fit. Perfect for Android users. Comes with charging case and extra ear tips.",
    category: "audio",
    brand: "Google",
    condition: "Working",
    listingType: "Sell",
    price: 5000,
    imageUrls: ["https://akm-img-a-in.tosshub.com/indiatoday/images/story/202108/google-pixel-buds-a-series-it2.jpg"],
    locality: "hadapsar",
    ownerId: "user_05",
    ownerName: "Rahul Khanna",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rahul",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-29",
    title: "HP LaserJet Pro MFP M130fw Printer",
    description: "All-in-one monochrome laser printer. Print, Scan, Copy, Fax. Wi-Fi enabled. Toner is about 50% full.",
    category: "other",
    brand: "HP",
    condition: "Working",
    listingType: "Sell",
    price: 12000,
    imageUrls: ["https://picsum.photos/seed/item29/600/400"],
    locality: "deccan-gymkhana",
    ownerId: "user_04",
    ownerName: "Priya Deshmukh",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=priya",
    ownerRating: 4.7,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-30",
    title: "Xiaomi Mi Band 6",
    description: "Fitness tracker with AMOLED display and blood oxygen monitoring. Used for a year, comes with charger.",
    category: "other",
    brand: "Xiaomi",
    condition: "Working",
    listingType: "Sell",
    price: 1500,
    imageUrls: ["https://picsum.photos/seed/item30/600/400"],
    locality: "wakad",
    ownerId: "user_05",
    ownerName: "Rahul Khanna",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rahul",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-31",
    title: "WD My Passport 1TB External HDD",
    description: "Western Digital My Passport 1TB portable external hard drive. USB 3.0 compatible. Great for backups or extra storage on the go. Formatted and ready to use.",
    category: "components",
    brand: "Western Digital",
    condition: "Working",
    listingType: "Sell",
    price: 3000,
    imageUrls: ["https://i.ytimg.com/vi/u0l5rgU7tzs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD%26rs%3DAOn4CLDR_r921d34EWhHM_9U6bkgOmswfQ"],
    locality: "pimpri-chinchwad",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-32",
    title: "Amazon Echo Dot (3rd Gen)",
    description: "Smart speaker with Alexa. Great for controlling smart home devices or playing music. Comes with original power adapter.",
    category: "other",
    brand: "Amazon",
    condition: "Working",
    listingType: "Sell",
    price: 2000,
    imageUrls: ["https://picsum.photos/seed/item32/600/400"],
    locality: "koregaon-park",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-33",
    title: "Wireless Gaming Mouse (Logitech G502)",
    description: "Logitech G502 Lightspeed wireless gaming mouse. Used for about a year, in excellent condition with no drift or double-clicking issues. Comes with the charging cable and all original weights.",
    category: "gaming",
    brand: "Logitech",
    condition: "Working",
    listingType: "Sell",
    price: 5500,
    imageUrls: ["https://oyster.ignimgs.com/wordpress/stg.ign.com/2019/05/Package1-720x404.jpg"],
    locality: "kothrud",
    ownerId: "user_02",
    ownerName: "Anjali Sharma",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=anjali",
    ownerRating: 4.9,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-34",
    title: "Old Nokia Feature Phone",
    description: "Classic Nokia E71 model with QWERTY keypad. Battery still holds a good charge. Perfect as a backup phone or for a digital detox. Comes with original charger.",
    category: "mobiles",
    brand: "Nokia",
    condition: "Working",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://cdn.dotpe.in/longtail/store-items/7994766/OgUrn70U.jpeg"],
    locality: "hadapsar",
    ownerId: "user_03",
    ownerName: "Vikram Singh",
    ownerAvatarUrl: null,
    ownerRating: 4.5,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-35",
    title: "Broken Laptop Screen (15.6 inch)",
    description: "15.6-inch laptop screen, broken/cracked. Donating for spare parts or repair by someone who can use the backlight, casing, or other components. Original from an HP laptop.",
    category: "components",
    brand: "Generic",
    condition: "For Spare Parts Only",
    listingType: "Donate",
    price: 0,
    imageUrls: ["https://www.lenovoservicecenterinhyderabad.in/images/screen-broken-reworking.webp"],
    locality: "baner",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-36",
    title: "USB-C to HDMI Adapter",
    description: "Connects USB-C devices like laptops and phones to HDMI monitors, TVs, or projectors. Supports 4K resolution. In perfect working condition.",
    category: "cables",
    brand: "Generic",
    condition: "Working",
    listingType: "Sell",
    price: 800,
    imageUrls: ["https://m.media-amazon.com/images/I/61dZnkijdIL.jpg"],
    locality: "wakad",
    ownerId: "user_05",
    ownerName: "Rahul Khanna",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rahul",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-37",
    title: "Old Router (TP-Link N300)",
    description: "Basic Wi-Fi router. Works well, but it's an older model (N300). Good for basic internet or as an access point.",
    category: "other",
    brand: "TP-Link",
    condition: "Working",
    listingType: "Sell",
    price: 500,
    imageUrls: ["https://picsum.photos/seed/item37/600/400"],
    locality: "pimpri-chinchwad",
    ownerId: "user_06",
    ownerName: "Deepak Patil",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=deepak",
    ownerRating: 4.6,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  },
  {
    id: "item-38",
    title: "Dead Laptop Battery (HP)",
    description: "Dead HP laptop battery. Not holding charge, but might be useful for someone needing the casing or individual cells for other projects. Donation for recycling.",
    category: "components",
    brand: "HP",
    condition: "For Spare Parts Only",
    listingType: "Donate",
    price: 0,
    imageUrls: [
      "https://m.media-amazon.com/images/I/61d335zIyJL._UF1000%2C1000_QL80_.jpg"
    ],
    locality: "kothrud",
    ownerId: "user_01",
    ownerName: "Rohan Kumar",
    ownerAvatarUrl: "https://i.pravatar.cc/150?u=rohan",
    ownerRating: 4.8,
    status: "Available",
    isFeatured: false,
    createdAt: new Date()
  }
];


export const conversations: (Conversation & { messages: ChatMessage[] })[] = [
    {
        id: 'convo-1',
        itemId: 'item-1',
        participants: ['user_02', 'user_01'],
        lastMessage: "Sounds good, let me know when you can meet.",
        lastMessageTimestamp: new Date("2025-10-09T10:30:00"),
        unreadCount: { 'user_01': 1 },
        messages: [
            { id: 'msg-1', senderId: 'user_01', text: 'I can accept your offer. I am free tomorrow afternoon.', timestamp: new Date("2025-10-09T10:28:00"), isRead: true },
            { id: 'msg-2', senderId: 'user_02', text: 'Sounds good, let me know when you can meet.', timestamp: new Date("2025-10-09T10:30:00"), isRead: false },
        ]
    },
    {
        id: 'convo-2',
        itemId: 'item-2',
        participants: ['user_03', 'user_02'],
        lastMessage: "Is this still available?",
        lastMessageTimestamp: new Date("2025-10-08T18:45:00"),
        unreadCount: { 'user_02': 1 },
        messages: [
            { id: 'msg-3', senderId: 'user_03', text: 'Is this still available?', timestamp: new Date("2025-10-08T18:45:00"), isRead: true },
        ]
    }
];

export const exchangeRequests: ExchangeRequest[] = [
    { id: 'req-1', itemId: 'item-1', requesterId: 'user_02', sellerId: 'user_01', status: 'Pending', createdAt: new Date() },
    { id: 'req-2', itemId: 'item-4', requesterId: 'user_03', sellerId: 'user_01', status: 'Accepted', createdAt: new Date() },
    { id: 'req-3', itemId: 'item-3', requesterId: 'user_01', sellerId: 'user_03', status: 'Completed', createdAt: new Date() },
    { id: 'req-4', itemId: 'item-2', requesterId: 'user_01', sellerId: 'user_02', status: 'Rejected', createdAt: new Date() },
];

export const notifications: Notification[] = [
    { id: 'notif-1', userId: 'user_01', type: 'request_received', text: 'Anjali Sharma sent a request for your Dell XPS 13 Laptop.', link: '/exchanges', isRead: false, createdAt: '1 day ago' },
    { id: 'notif-2', userId: 'user_02', type: 'request_accepted', text: 'Rohan Kumar accepted your request for the assorted cables.', link: '/exchanges', isRead: true, createdAt: '12 hours ago' },
    { id: 'notif-3', userId: 'user_03', type: 'new_rating', text: 'Rohan Kumar left you a 5-star rating!', link: '/users/user_03', isRead: true, createdAt: '4 days ago' },
];

export const itemCategories: string[] = ['Laptops', 'Phones', 'Tablets', 'Monitors', 'Cameras', 'Audio', 'Accessories', 'Other'];

export const categories: AppCategory[] = [
  { id: 'mobiles', name: 'Mobiles', icon: Smartphone, slug: 'mobiles' },
  { id: 'laptops', name: 'Laptops', icon: Laptop, slug: 'laptops' },
  { id: 'keyboards', name: 'Keyboards', icon: Keyboard, slug: 'keyboards' },
  { id: 'monitors', name: 'Monitors', icon: Monitor, slug: 'monitors' },
  { id: 'cables', name: 'Cables', icon: Cable, slug: 'cables' },
  { id: 'audio', name: 'Audio', icon: Headphones, slug: 'audio' },
  { id: 'components', name: 'Components', icon: MemoryStick, slug: 'components' },
  { id: 'gaming', name: 'Gaming', icon: Gamepad2, slug: 'gaming' },
  { id: 'drones', name: 'Drones', icon: ToyBrick, slug: 'drones' },
  { id: 'other', name: 'Other', icon: SquarePlus, slug: 'other' },
];

export const locations: Location[] = [
    { name: 'Kothrud, Pune', slug: 'kothrud' },
    { name: 'Viman Nagar, Pune', slug: 'viman-nagar' },
    { name: 'Koregaon Park, Pune', slug: 'koregaon-park' },
    { name: 'Deccan Gymkhana, Pune', slug: 'deccan-gymkhana' },
    { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad' },
    { name: 'Hadapsar, Pune', slug: 'hadapsar' },
    { name: 'Hinjawadi, Pune', slug: 'hinjawadi' },
    { name: 'Baner, Pune', slug: 'baner' },
    { name: 'Wakad, Pune', slug: 'wakad' },
    { name: 'Aundh, Pune', slug: 'aundh' },
];


export const mockRepairShops: RepairShop[] = [
    { id: 'shop1', name: 'Pune Mobile Experts', locality: 'kothrud', rating: 4.8, services: ['Screen Repair', 'Battery'] },
    { id: 'shop2', name: 'QuickFix Electronics', locality: 'viman-nagar', rating: 4.6, services: ['Screen Repair', 'Water Damage'] },
    { id: 'shop3', name: 'Gadget Gurus', locality: 'koregaon-park', rating: 4.9, services: ['All Brands', 'Software'] },
];

    

    

    

    